services:
  - type: web
    name: pancake-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
    rootDir: python/CNN  # ← 追加（app.py がこの中にあるため）

build:
  pythonVersion: 3.9.17
