services:
  - type: web
    name: pancake-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
    rootDir: pancake

build:
  pythonVersion: 3.9.17
