services:
  - type: web
    name: pancake-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: pancake

build:
  pythonVersion: 3.9.17
